### PR TITLE
Complete PR 688

### PR DESCRIPTION
**Pull request by andersonfrailey**
This PR simply resolves the merge conflicts in PR #688 by @hayleefay.

cc @hdoupe

### CODE REVIEW

**Comment by hdoupe** [comment]
Thanks @andersonfrailey. This looks good. Can you change the bokeh version to `>=0.12.7` in:
- `conda-requirements.txt`
- `distributed/Dockerfile`

**Comment by andersonfrailey** [comment]
@hdoupe yep. Added in latest commit.

**Comment by hdoupe** [comment]
LGTM. Thanks @andersonfrailey

**Comment by hdoupe** [comment]
Also thanks for opening this @hayleefay. Sorry for letting it sit open for so long.

**Pull request merged**
