### PR TITLE
Add test for eitc rate greater than 1

### PR DESCRIPTION
**Pull request by hdoupe**
This test exposes the bug found in issue #596

### CODE REVIEW

**Comment by martinholmer** [comment]
@hdoupe,  Why are you adding a TaxBrain test to detect a perfectly valid parameter value?
Look at `taxcalc/current_law_policy.json` to see that `eitc_rt` can have **any** non-negative value.
What am I missing?  I don't see why this TaxBrain test is needed.  It seems wrong, not just unneeded.

**Comment by hdoupe** [comment]
@martinholmer I added this as a regression test.  I wanted to make sure that we didn't have any issues in the future with EITC_rt parameter values or values for similar parameters being rounded down to 1.

**Comment by martinholmer** [comment]
Oh, the test is to see if values of `_EITC_rt` greater than one are **allowed**.
OK, I missed that.  So, adding the test seems fine.

But I don't understand the new test's docstring:
```
    def test_taxbrain_eitc_rt_greater_than_1(self):
        """
        Transfer over the regular tax capital gains to AMT
        """
```

**Comment by hdoupe** [comment]
@martinholmer Thanks for pointing that out.  I copied and pasted from another function and forgot to change the docstring.  The latest commit updates the docstring.

**Comment by hdoupe** [comment]
#674 test is covered in PR #706

**Pull request closed without merging**
