### PR TITLE
New content for getting started, about, and nav menu

### PR DESCRIPTION
**Pull request by jessmc**
In this pull request:
- Created the page Getting Started with some content and youtube video 'Welcome to TaxBrain'
- Added youtube video 'Welcome to Open Source Policy Center' to about page between 'Our Mission' and 'Our History'
- Made link changes to the navigation menu in the header

Thank you!

### CODE REVIEW

**Comment by MattHJensen** [comment]
Thanks for this one too. Also early next week for feedback.

**Comment by hdoupe** [comment]
@jessmc We moved all of the flatblock contents from the django admin portion of the site into the repo.  It looks like there is a small merge conflict.  I tried to resolve it but it doesn't look like that changed anything.  Would you mind taking a look at this before I break something?

Otherwise, this looks great.  We are pushing a new version of PolicyBrain to the test server today.  So, if you could resolve this by 3 or 4 PM EST that would be great.  If not, I should be able to resolve the conflict.

cc @MattHJensen @jessmc

**Comment by jessmc** [comment]
Hi @hdoupe  ! I just took a look and think I was able to resolve the conflict. Please let me know if this helps, and if you need anything else from me!
Thanks, 
Jessica

**Comment by hdoupe** [comment]
@jessmc Looks great. Thanks for the quick response!

**Pull request merged**
