### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by hdoupe**
This PR updates the README.md document.  I tried to give a description of PolicyBrain that had a technical tilt.  I included the new local deployment steps.  I still need to add the production and test server deployment steps.  However, I think this would be a little too much for the README.md document.  So, I think we should move the deployment information to a separate document.  I also need to add a contributing guide.

I appreciate all feedback on this document.  It could be formatted completely differently if we think that would be helpful.  I recommend checking out the README.md documents for other projects such as [Pandas](https://github.com/pandas-dev/pandas) and [NumPy](https://github.com/numpy/numpy).  I liked NumPy's concise style and use of bullet points.  I thought that made it easier to read.  It seems like there is a fairly large variation in README styles.  For example, compare Scipy's [README](https://github.com/scipy/scipy) with NumPy's.

### CODE REVIEW

**Comment by martinholmer** [comment]
@hdoupe,  Big improvement in the `README.md` text.  Thanks.

**Comment by MattHJensen** [comment]
Looks great. +1

**Comment by hdoupe** [comment]
@brittainhard In the following line, I wanted to briefly describe PolicyBrain's technology stack.  Do you have any input on how this was worded?  

"PolicyBrain is a Django app which is deployed on Heroku and uses Flask, Celery, and Redis to schedule jobs."  

Specifically, I'm not sure if I got the "...uses Flask, Celery, and Redis to schedule jobs." part right.

**Comment by brittainhard** [comment]
@hdoupe i'll take a look at that wording.

**Comment by hdoupe** [comment]
Thanks @brittainhard

**Comment by brittainhard** [comment]
@hdoupe I think you are on point with the stack description. LGTM.

However, this got me thinking. I'm not sure someone can get the local application running without `taxpuf`. This is an issue that is long-standing. We need a way for people to develop on the application without needing `taxpuf`, since it is private.

I don't know if there is an issue open for this or not. @MattHJensen @PeterDSteinberg do you recall if we came up with a solution for this?

**Comment by hdoupe** [comment]
@brittainhard Thanks!

> However, this got me thinking. I'm not sure someone can get the local application running without taxpuf. This is an issue that is long-standing. We need a way for people to develop on the application without needing taxpuf, since it is private.

I ran into this problem this afternoon.  I re-cloned my local PolicyBrain directory after the release and forgot to include the PUF file until this afternoon.  I was able to look at the parameter input pages, but I got an error when I tried to submit a reform.  By the end of the year, we will have an option for users to use the CPS.  At that point, you could run the full model without the PUF file.

**Comment by martinholmer** [comment]
@brittainhard said in the discussion of PR #702:
> However, this got me thinking. I'm not sure someone can get the local application running without `taxpuf`. This is an issue that is long-standing. We need a way for people to develop on the application without needing `taxpuf`, since it is private.

This problem will be solved once PolicyBrain starts using the taxcalc>=0.12.0 package.  One of the enhancements in 0.12.0 is to make the `taxbrain interface` or `tbi` functions work with either the `puf.csv` or `cps.csv` input files.  See [Tax-Calculator pull request 1577](https://github.com/open-source-economics/Tax-Calculator/pull/1577) for details.

@MattHJensen @hdoupe @GoFroggyRun

**Comment by hdoupe** [comment]
Unless someone objects, I plan to merge this on Wednesday (10/25).

**Pull request merged**
