### PR TITLE
Convert DependentCredit_before_CTC from bool to int

### LINKED ISSUE #765: Handle future year reforms for checkboxes
There's one provision in TCJA Senate Modified Mark's proposal that introduces "stack[ing] the dependent credit before the child tax credit" in 2018, and then repeals it starting 2026. 

Currently, this boolean parameter `_DependentCredit_before_CTC` is handled using a checkbox on TaxBrain: checked box indicates true while unchecked one represents false, which I believe is a concise way of integrating such boolean parameters. It seems that, however, such format won't allow users to specify any further reforms for future years.  

Since it would be desirable to handle both House and Senate reforms in TaxBain's GUI, we might want to modify, at least for `_DependentCredit_before_CTC` parameter, the way of handling boolean fields to allow future year reforms. However, I haven't come up with an ideal way to deal with it. 

Any comments, concerns or remarks would be helpful. @martinholmer @MattHJensen @hdoupe

### PR DESCRIPTION
**Pull request by hdoupe**
Resolves #765.  This PR treats `DependentCredit_before_CTC` as an integer instead of a boolean parameter which allows the user to very the parameter's value over time.

EDIT:
Old behavior:
screen shot 2017-12-19 at 5 12 11 pm

New behavior:
screen shot 2017-12-19 at 5 12 49 pm

### CODE REVIEW

**Comment by hdoupe** [comment]
Are there any other boolean parameters that we would like to convert into comma separated value parameters?  

My plan is to only convert the ones where we see an obvious use case for allowing changes over time.  If we like the behavior introduced for these select parameters, then we can convert the rest of the boolean parameters.  I think this will minimize the number of changes to the database.

cc @MattHJensen @martinholmer @codykallen

**Comment by MattHJensen** [comment]
@hdoupe, once you feel comfortable with the database changes, I think we should make this change for all boolean parameters, as it is very difficult to anticipate what could or couldn't be phased in over time or sunset.

**Comment by martinholmer** [comment]
@hdoupe said:
> This [PolicyBrain] PR [#782] treats `DependentCredit_before_CTC` as an integer instead of a boolean parameter which allows the user to very the parameter's value over time.

OK, but this parameter is boolean in Tax-Calculator.  So that means the JSON reform file TaxBrain generates must have them as boolean even though they are presented as 0s and 1s in the TaxBrain GUI.

Is there a reason the GUI can't use comma-separated boolean values?

**Comment by hdoupe** [comment]
@MattHJensen Ok, that makes sense.  I'll get this on the test app today.  If everything goes well, then I will apply this change to the rest of the boolean parameters.

**Comment by hdoupe** [comment]
@martinholmer asked:
> OK, but this parameter is boolean in Tax-Calculator. So that means the JSON reform file TaxBrain generates must have them as boolean even though they are presented as 0s and 1s in the TaxBrain GUI.
> 
> Is there a reason the GUI can't use comma-separated boolean values?

The GUI can tolerate comma separated boolean values.  However, I think that we should also allow the submission of 1/0 since they are logically equivalent.

**Comment by hdoupe** [comment]
@martinholmer I'm getting the following error when I submit this reform:
screen shot 2017-12-20 at 10 05 15 am

A simpler example of this reform is run here:
```
import taxcalc

policy_dict = {
    u'policy': {
        2019: {
            u'_DependentCredit_before_CTC': [1],
        },
    },
    u'growdiff_response': {},
    u'consumption': {},
    u'behavior': {},
    u'growdiff_baseline': {}
}

ew  = taxcalc.tbi.reform_warnings_errors(policy_dict)

print("errors warnings for: ")
print(policy_dict)
print('\n')
print(ew)

policy_dict["policy"][2019]["_DependentCredit_before_CTC"] = [1.0]

ew = taxcalc.tbi.reform_warnings_errors(policy_dict)
print("\nerrors warnings for: ")
print(policy_dict)
print('\n')
print(ew)
```

I get the following output:
```
(aei_dropq) HDoupe-MacBook-Pro:PolicyBrain henrydoupe$ python tc_pr_1775.py 
errors warnings for: 
{u'policy': {2019: {u'_DependentCredit_before_CTC': [1]}}, u'growdiff_response': {}, u'behavior': {}, u'consumption': {}, u'growdiff_baseline': {}}


{'errors': '', 'warnings': ''}

errors warnings for: 
{u'policy': {2019: {u'_DependentCredit_before_CTC': [1.0]}}, u'growdiff_response': {}, u'behavior': {}, u'consumption': {}, u'growdiff_baseline': {}}


{'errors': 'ERROR: 2019 _DependentCredit_before_CTC value 1.0 is not boolean\n', 'warnings': ''}
```

It seems like 1.0 is not a valid boolean according to Tax-Calculator even though we also have:
```
In [1]: bool(1.0) == bool(1) == bool(True)
Out[1]: True
```

PolicyBrain reads the user input from the GUI as strings.  The strings with digits are converted to python floats.  I could add a special case for the boolean parameters that are entered as 1/0/1.0/0.0 that converts them to 1/0 or True/False.  However, I think a better solution would be for Tax-Calculator to accept 1.0 and 0.0 as valid boolean values.  @martinholmer what are your thoughts on this?

**Comment by MattHJensen** [comment]
Just my 2 cents, I am more eager for TaxBrain to be able to accept True/False than for either TaxBrain or Tax-Calculator to accept 1.0, 1, 0, 0.0. We just have so many numeric inputs, including switches, it refreshing to differentiate switches.

**Comment by hdoupe** [comment]
@MattHJensen Thanks for your insight.  I moved your comment to issue #786.  Sorry, I probably should have left this PR open longer.  I was in a bit of a rush to get this merged, get a pre-release up, and move on to #763.  I should have waited longer to make sure that we were all on board.

**Pull request merged**
