### PR TITLE
Rename macro elasticity label and remove dropdown menu in its result page

### LINKED ISSUE #673: Fix mislabeled "Macro Elasticities Simulation" button
On the [Choose a Dynamic Simulation Type](http://www.ospc.org/dynamic/17527/?start_year=2017) page, there is a button labeled "Macro Elasticities Simulation".  But when you click on that button and go to the [macro page](http://www.ospc.org/dynamic/macro/17527/?start_year=2017), there is only one elasticity to specify.

So, to reduce the chance of user confusion about where the other elasticities are, it seems as if the button should be labeled "Macro Elasticity Simulation".

Also, the title of the [macro page](http://www.ospc.org/dynamic/macro/17527/?start_year=2017) should be changed from "Macroeconomic Elasticities" to "Macroeconomic Elasticity Simulation" and the text, which was copied and pasted from the docstring in the `taxcalc/macro_elasticity.py` file, needs to reflect the corrections and revisions made in [Tax-Calculator pull request 1572](https://github.com/open-source-economics/Tax-Calculator/pull/1572).

And finally, the title on the one-line table is confusing.  Here is what it looks like now:

screen shot 2017-10-05 at 6 49 30 am

The label to the far left of the line of results is fine.  The title should be changed to read something like:
`Percentage Change in GDP`.

@MattHJensen @feenberg @hdoupe @GoFroggyRun

### PR DESCRIPTION
**Pull request by GoFroggyRun**
This PR fixes #673 and #683. The new page/button would look something like:

screen shot 2017-10-05 at 10 54 29 am

and

screen shot 2017-10-05 at 10 54 23 am

and finally

screen shot 2017-10-05 at 10 54 04 am

### CODE REVIEW

**Comment by martinholmer** [comment]
@GoFroggyRun, your pull request #684 looks good as far as it goes.
Can you also change the table title (which appears just above the table) along the lines suggested by [this 673 comment](https://github.com/OpenSourcePolicyCenter/PolicyBrain/issues/673#issue-261439444)?

**Comment by GoFroggyRun** [comment]
@martinholmer thanks for catching this. I changed the title to `Percentage Change in GDP`: 

screen shot 2017-10-05 at 12 53 37 pm

**Comment by martinholmer** [comment]
@GoFroggyRun said:
> I changed the title to Percentage Change in GDP.

Well, I guess the terms for different parts of a table can be confusing.

I would say that in commit 06f3747e5 you changed the **row label**, not the **title**.

What I would call the title is right above the year table row.

screen shot 2017-10-05 at 2 14 26 pm

What I was asking you to do was to change `Elasticity of GDP wrt 1 - Average Marginal Tax Rate` to something like `Percentage Change in GDP`.

The current title is simply incorrect.  The table does not contain elasticities (the one assumed elasticity was specified on the Macro-Elasticity input parameter page) but rather contains the proportional change in GDP caused by the interaction of the assumed elasticity and the change in the average marginal tax rate.

Sorry about the confusion in my earlier request.

But we do need to change the incorrect title.

@MattHJensen @Amy-Xu @hdoupe

**Comment by martinholmer** [comment]
Commit b27c6fae5a looks great!  Thanks, @GoFroggyRun, and sorry for my confusing suggestions.

**Comment by GoFroggyRun** [comment]
@martinholmer my bad, I thought your intention were to un-symbolize the `%` sign. I reverted the row label change and updated the title. 

screen shot 2017-10-05 at 3 14 04 pm

**Comment by hdoupe** [comment]
@GoFroggyRun LGTM. Is this ready to merge?

**Comment by GoFroggyRun** [comment]
Yep @hdoupe

**Pull request merged**
