### PR TITLE
Fix btax backend bug caused by PR #641

### PR DESCRIPTION
**Pull request by hdoupe**
Address #637 and #641

### CODE REVIEW

**Comment by brittainhard** [comment]
@hdoupe have you tested this fix yet?

**Comment by hdoupe** [comment]
@brittainhard Yes, it seemed to work fine.

**Comment by hdoupe** [comment]
@brittainhard is everything working OK?

**Comment by brittainhard** [comment]
@hdoupe testing it right now.

**Comment by hdoupe** [comment]
Great thanks @brittainhard

**Comment by brittainhard** [comment]
@hdoupe looks like its fixed! I'll get this PR merged.

**Comment by hdoupe** [comment]
Awesome, thanks for taking a look at it.

**Pull request merged**
