### PR TITLE
Sphinx Documentation

### LINKED ISSUE #691: Set up Sphinx Documentation Structure
We will be using Sphinx for documentation. Include basic structure and dependencies.

### PR DESCRIPTION
**Pull request by brittainhard**
Closes #691

### CODE REVIEW

**Comment by brittainhard** [comment]
@hdoupe @MattHJensen I think we need a new README.md that describes what the application does, and what problems it solves. This can also go on the index page of the documentation. Would either of you be up for writing it?

**Comment by hdoupe** [comment]
Thanks @brittainhard 

@MattHJensen I can work on this.  I would appreciate it if you gave me a quick outline.  Then, I could fill in the rest.  How does that sound?

**Comment by martinholmer** [comment]
@brittainhard added `puf.csv` to the `.gitignore` file in pull request #692.

The `puf.csv.gz` file was already in the `.gitignore`, so I'm confused about which version of the file PolicyBrain has on the AWS instances.  I saw some code that read `puf.csv.gz`, but I have'nt seen any code that reads `puf.csv`.  So, I'm wondering why you have to add `puf.csv` to `.gitignore` because as far as I can tell it is never used by PolicyBrain (locally or on AWS).

Can you help me understand how things work with respect to reading the PUF data?

@MattHJensen @hdoupe @GoFroggyRun

**Comment by MattHJensen** [comment]
@hdoupe, no need to wait for an outline from me, go ahead and say it how you see it. I'll give you feedback if I think anything is wrong or could be improved.

**Comment by brittainhard** [comment]
@martinholmer CCC needs `puf.csv` unzipped.

**Comment by brittainhard** [comment]
Gonna merge this and start working on filling out the documentation.

**Pull request merged**
