### PR TITLE
Back-end for not_avail.html page

### PR DESCRIPTION
**Pull request by hdoupe**
This PR adds renders the `not_avail.html` page (see #874) when an error is thrown while rendering simulation results.

For TaxBrain:

screen shot 2018-03-28 at 11 36 05 am

For CCC:

screen shot 2018-03-28 at 11 36 43 am

### CODE REVIEW

**Comment by hdoupe** [comment]
After the previous commits the pages look like:

screen shot 2018-03-28 at 11 46 29 am

screen shot 2018-03-28 at 11 47 28 am

**Comment by hdoupe** [comment]
@GoFroggyRun @MattHJensen can you review?

**Comment by GoFroggyRun** [comment]
@hdoupe looks good to me! Once this got merged, I'll have a separate PR open that breaks up the headers.

**Comment by hdoupe** [comment]
Great, thanks for the review @GoFroggyRun

**Pull request merged**
