### PR TITLE
Refactor test functions

### PR DESCRIPTION
**Pull request by hdoupe**
This PR cleans up the test suites in the `taxbrain` and `dynamic` directories.  The main focus is on the views functions.  This PR is associated with the test push issue #699.

TODO: 
- [x] Move duplicated data creation code into functions
- [x] Use `do_micro_sim` for all typical micro-simulation jobs.  Prior to this PR this function was used primarily in the `dynamic` test suite and not in the `taxbrain` test suite.  "Typical" means that we expect a 302 response on the redirect and a 200 response when we GET the results url.
- [tabled for another issue] Add flexible parameter checking to make sure parameters are passed to the models correctly

### CODE REVIEW

**Comment by hdoupe** [comment]
@brittainhard @PeterDSteinberg @GoFroggyRun This PR is ready for review.  It makes some substantial changes to the test suite.  I would appreciate it if you all could find some time to take a look at it.

**Comment by brittainhard** [comment]
@hdoupe this looks good to me. Definitley simplifies things.

**Comment by hdoupe** [comment]
@brittainhard Ok, thanks for reviewing.

**Comment by hdoupe** [comment]
I plan to merge this at the end of the day.  

Future improvements could include:
1. Applying the refactoring strategy to the macro elasticity simulation model and the behavioral model.  This PR focused primarily on TaxBrain and the Dynamic model since this is where most of the current development work is focused.
2. Use the [pytest monkeypatch plug-in](https://docs.pytest.org/en/latest/monkeypatch.html) for safer mocking

**Pull request merged**
