### PR TITLE
[WIP] Add button to allow CPS as input data source 

### PR DESCRIPTION
**Pull request by GoFroggyRun**

### CODE REVIEW

**Comment by GoFroggyRun** [comment]
@hdoupe this is how I'd like to add the CPS button. I'm having trouble to have those options displayed properly, even if for most part I was mimicking the "Start Year" button.

**Comment by GoFroggyRun** [comment]
I'm confused why the button shows nothing: when I substitute `start_years` for `data_sources`, and `start_year` for `default_source`, the drop down does show different years as specified in `constants.py`. But I can't quite figure out why `data_sources`, `default_source` won't work.

**Comment by GoFroggyRun** [comment]
@hdoupe Thanks! Conflicts are resolved.

**Comment by hdoupe** [comment]
Thanks @GoFroggyRun

**Comment by GoFroggyRun** [comment]
Closing this in favor of #835

**Pull request closed without merging**
