### PR TITLE
Add database docs

### PR DESCRIPTION
**Pull request by hdoupe**
Goals for this PR:

- [x] Add instructions for setting up a local Postgres server
- [x] Add instructions for running a local instance of PolicyBrain using the local Postgres server
- [x] Add some database migrations best practice-type procedures in an effort to minimize the number of database misadventures

### CODE REVIEW

**Comment by GoFroggyRun** [comment]
+1 This PR LGTM. 

I was able to get Postgres server set-up on my local following the instructions.

**Comment by hdoupe** [comment]
@GoFroggyRun would you mind reviewing the database back up procedure that I outlined in the DATABASE.md file?

@Kpinkelman Thanks for the notes on the local deployment setup documentation! Please, let me know if you have any more questions or feedback

**Comment by GoFroggyRun** [comment]
LGTM, +1

**Comment by hdoupe** [comment]
Thanks for the review @GoFroggyRun.

**Pull request merged**
