### PR TITLE
Add CNN to media coverage 

### PR DESCRIPTION
**Pull request by GoFroggyRun**
Per the post [here](http://www.cnn.com/2017/12/13/politics/calculate-americans-taxes-senate-reform-bill/), this PR adds CNN to media coverage.

### CODE REVIEW

**Comment by GoFroggyRun** [comment]
@hdoupe can we have this PR included in the new update?

**Comment by hdoupe** [comment]
@GoFroggyRun are the commits fix render issue, fix wrong title for each prints, and fix csv file name issue related to adding the CNN logo?

**Comment by GoFroggyRun** [comment]
@hdoupe that right. For some reason, those commits in #780 got carried over here. I'll take care of them.

**Comment by hdoupe** [comment]
@GoFroggyRun I merged #780.  I'm not sure why the commits from #780 are still shown in #781.  GitHub still shows 6 files changed and the diff seems to show the diff with the master branch before #780 was merged.  I'm not sure what the problem is. Do you have any ideas?  I just want to make sure that by merging this we aren't writing over something changed in #780.

**Comment by GoFroggyRun** [comment]
@hdoupe yeah. Probably because I didn't update my master after your merge I guess. Now git only shows two file changes. We should be good.

**Comment by hdoupe** [comment]
Cool, thanks @GoFroggyRun

**Pull request merged**
